rmdir /s /q build2
mkdir build2
cd build2
cmake -DCMAKE_SYSTEM_VERSION=10.0.19041.0 -DCMAKE_GENERATOR_TOOLSET=v142 -DCMAKE_BUILD_TYPE=DEBUG -DLWS_WITH_SSL=1 -DLWS_WITHOUT_EXTENSIONS=1 -DLWS_WITH_ZIP_FOPS=0 -DLWS_WITH_ZLIB=0 -DLWS_HAVE_EVENTFD=0 --fresh -A  x64 ..
pause